name = "FortrANN"
version = "0.1.0"
license = "license"
author = "*******"
maintainer = "********"
copyright = "Copyright 2024, *******"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
csv-fortran = { git="https://github.com/jacobwilliams/csv-fortran.git" }